services:

  

  web-server:
    image: gabrielchavezr/aeronave_webapi:v1
    build:
      context: .
      dockerfile: ./Aeronave.WebApi/Dockerfile
    ports:
      - "8181:80"
      - "4433:443"
    environment:
      ConnectionStrings:PedidoDbConnectionString: "Server=mssql-server;Database=AeronaveDb;User Id=sa; Password=Gabriel123+"
   
    depends_on:
      - mssql-server
   
  mssql-server:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      MSSQL_SA_PASSWORD: "Gabriel123+"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1434:1433"
    volumes:
      - 'mssql-server-data:/var/mssql/data'
    container_name: "mssql-server"
    hostname: "mssql-server"
    
volumes:
  mssql-server-data:
