services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04    
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Gabriel123+
    ports:
      - "1434:1433"
  
  web-api:  
    image: gabrielchavezr/aeronave_webapi:v1
    environment:  
      - ASPNETCORE_ENVIRONMENT=Development  
    ports:  
      - "8181:80"  
