name: Execute SQL Scripts on SQL Server

on:
  push:
    branches: [ "master" ]
jobs:
  execute-sql-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 17

    - name: Install dependencies
      run: npm install tedious

    - name: Execute SQL scripts
      run: |
        node -e "
        const fs = require('fs');
        const path = require('path');
        const Connection = require('tedious').Connection;
        const Request = require('tedious').Request;
        const config = {
          server: '${{ secrets.SP_SQL_SERVER_HOST }}',
          options: {
            port: ${{ secrets.SP_SQL_SERVER_HOST_PORT }},
            encrypt: true,
            database: 'BD_PRUEBAS'
          },
          authentication: {
            type: 'default',
            options: {
              userName: 'sa',
              password: '${{ secrets.SP_SQL_SERVER_PASSWORD }}'
            }
          }          
        };

        const connection = new Connection(config);

        connection.on('connect', (err) => {
          if (err) {
            console.error('Failed to connect:', err.message);
            return;
          }

          console.log('Connected to SQL Server.');

          const scriptsFolder = 'scripts';
          const scripts = fs.readdirSync(scriptsFolder);

          scripts.forEach((script) => {
            const scriptPath = path.join(scriptsFolder, script);
            const sqlScript = fs.readFileSync(scriptPath, 'utf8');

            const request = new Request(sqlScript, (error) => {
              if (error) {
                console.error('Error executing ${script}:', error.message);
              } else {
                console.log('${script} executed successfully.');
              }
            });

            connection.execSql(request);
          });

          connection.close();
        });
        "
