name: Ejecucion scripts SQL Server

on:
  push:
    branches: [ "master" ]
jobs:
  execute-sql-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Ejecutar scripts de SQL desde carpeta
      run: |
          # Obtiene la lista de archivos .sql en la carpeta 'scripts'
          $scripts = Get-ChildItem -Path scripts -Filter *.sql

          foreach ($script in $scripts) {
            # Ejecuta el script utilizando Invoke-SqlCmd
            Invoke-SqlCmd -ServerInstance '34.118.139.240,1434' -Database 'BD_PRUEBAS' -Username 'sa' -Password Gabriel123+ -InputFile $script.FullName
          }


