name: Ejecucion scripts SQL Server

on:
  push:
    branches: [ "master" ]
jobs:
  execute-sql-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Ejecutar scripts de SQL desde carpeta
      run: |
          # Obtiene la lista de archivos .sql en la carpeta 'scripts'
          scripts=$(find scripts -type f -name '*.sql')

          for script in $scripts; do
            # Ejecuta el script utilizando sqlcmd
            sqlcmd -S 34.118.139.240,1434 -d BD_PRUEBAS -U sa -P Gabriel123+ -i "$script"
          done




